### ISSUE TITLE
iOS 9.0

### ISSUE THREAD

**Issue by fernandodev** [XWebView/XWebView#15]
Hi,

Now in iOS 9.0 there are two new methods:
1. `loadFileURL(_:allowingReadAccessToURL:)
   (New in iOS 9.0)`

and
1. `loadData(_:MIMEType:characterEncodingName:baseURL:)
   (New in iOS 9.0)`
- [WkWebView](https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKWebView_Ref/#//apple_ref/occ/instm/WKWebView/loadData:MIMEType:characterEncodingName:baseURL:)

So for `1` it isn't necessary `XWebView`'s method anymore and `2` solves the problem covered by my PR `loadHTMLString(html: String, allowingReadAccessToBaseURL baseURL: NSURL?) -> WKNavigation?`, because it can now access by fileURL. 

I'm figuring out a way to refactor XWebView to provides only plugins integration (swift <-> javascript). What do you think about that? 

In a few months there is no reason to be worried about iOS 8.\* back compatibility.

**Comment by xwv** [comment]
Yes, I think we can remove the back compatibility for iOS 8 when its market share drops below 10%.
There are some efforts for iOS 9 support in the last commit. On iOS 9, the WKWebView's native loadFileURL and loadHTMLString are preferred. Meanwhile, XWebView provides "polyfills" (through http server) for the 2 methods with exactly the same API. The new loadData method has no such "polyfill" because it seems infeasible.

Technically, it should be simple to remove the iOS 8 support which is very loosely coupled with the core function. So I don't think it needs to refactor.

Actually, I have many ideas but lack time to do. You can check the [TODO page](https://github.com/XWebView/XWebView/wiki/TODO) I just created.
I would like to invite you to join the project if you have interest to contribute further.  I expect to listen your suggestions and opinions.

**Comment by fernandodev** [comment]
Nice and thank you @xwv , 

I'll take a look on _TODO_.
