### ISSUE TITLE
Example for instantiating native classes?

### ISSUE THREAD

**Issue by nfarina** [XWebView/XWebView#47]
I'm trying to figure out how to use this functionality described in the README:

> A plugin can have multiple instances. In this case, an initializer is mapped to the function of constructor.

I tried passing `MyClass.self` to `loadPlugin`, and that does seem to create a `MyClass` global in JS, but I can't figure out how to instantiate `MyClass` in JS. Calling `new MyClass()` doesn't work of course.

Any tips?

**Comment by xwv** [comment]
Please see the [Echo](https://github.com/XWebView/Sample/blob/master/Sample/Plugins/Echo.swift) sample plugin. For constructor, you have to implement the `scriptNameForSelector:` method, return empty string while the input selector is the designate initializer for constructor. The initializer will be invoked while a new instance is created on script side.

To load a constructible plugin, you have to create an instance of the class and call `loadPlugin`, see [this](https://github.com/XWebView/Sample/blob/master/Sample/ViewController.swift#L29)

Yes, the interface is awkward. I'm considering to redesign it.

BTW, because the communication is async, on javascript side, `new` will return a promise instead of the new object. See [this](https://github.com/XWebView/Sample/blob/master/Sample/index.html#L26).

**Comment by nfarina** [comment]
Thanks so much for the instruction! I got it working with your help - I was missing the part where I needed my class to conform to the `XWVScripting` protocol.

I didn't know about the Sample project - it's extremely helpful. I would suggest linking to that from the XWebView main repository. I'll make a PR in case you'd like to do that.
