### ISSUE TITLE
How to convert XWVScriptObject to a dictionary

### ISSUE THREAD

**Issue by trevorwang** [XWebView/XWebView#49]
``` javascript

window.webview.post = function(cmd,para){
    if(isIOS){
        var message = {}
        message.meta = {
            cmd:cmd
        }
        message.para = para || {}
        window.webview.post(message)
    }
}
```

``` swift
class PostAction:NSObject {
    func post(message:AnyObject?) {
        //received an XWVScriptObject but a dictionary is expected
    }
}
```

I have loaded the `PostAciton` as a plugin

**Comment by xwv** [comment]
I guess you want to pass the `message` by value(dictionary) instead of reference(XWVScriptObject).

XWebView will pass parameter by value if its type is null, string, number, boolean or a simple object type. A simple object type means itself and its descendant must be one of following object types:
`ArrayBuffer`, `Blob`, `Boolean`, `DataView`, `Date`, `File`, `FileList`, `Float32Array`, `Float64Array`, `ImageData`, `Int16Array`, `Int32Array`, `Int8Array`, `MessagePort`, `Number`, `RegExp`, `String`, `Uint16Array`, `Uint32Array`, `Uint8Array`, `Uint8ClampedArray`, `Array`, `Map`, `Object`, `Set`.

For your case, I believe that `para` argument is not a simple object. A common pitfall is that it has a function property.

**Comment by trevorwang** [comment]
Thanks @xwv .
I fixed this by converting the object to json string and then parsing to object again.
