### ISSUE TITLE
Extend plugin class

### ISSUE THREAD

**Issue by githubdoramon** [XWebView/XWebView#60]
Hi, I tried to create a base class for a plugin, and then extend it to add other functions depending on where I would use, but when I do that, only the new functions work, and not the bsae ones from the initial class. Any ideias why this happens?

Example:

```

class NativePlugin : NSObject {
    func bla() {
    }
}
```

```
class ExtendPlugin : NativePlugin {
    func ble() {
    }
}
```

If I add ExtendedPlugin, only ble() works, nut no bla()

**Comment by xwv** [comment]
This is by design. Inherited methods will not be exported to JavaScript.
For workaround, override methods in subclass.

**Comment by githubdoramon** [comment]
Why this is the expected/design behavior?

**Comment by xwv** [comment]
In short, this is for simplicity and performance. Because it avoids to go through ancestors of plugin objects.
A principle of design is that plugin object should be proxy object instead of real functional object. See [proxy pattern](https://en.wikipedia.org/wiki/Proxy_pattern)
A proxy object commonly conforms to a protocol rather than inherits methods from super class.
