### ISSUE TITLE
unescaped ' in string will cause problem

### ISSUE THREAD

**Issue by oldshuren** [XWebView/XWebView#7]
unescaped ' in string will cause problem. For example in the echo example, put "'" in the message, there will no callback.

I think the "'" is not escaped in javascript string literal

**Comment by oldshuren** [comment]
js to native is fine, native to js has problem.

**Comment by soflare** [comment]
Fixed.
Thanks for reporting the issue.

**Comment by oldshuren** [comment]
Thanks for quick fix! 

By the way, when can I see it from Pod?

**Comment by soflare** [comment]
Next week hopefully.
BTW, are you planing to use XWebView in your production, or just have a try?
Let me know if there is anything I can help out.

**Comment by oldshuren** [comment]
We're trying to now. Works perfectly, thanks!

**Comment by atwoodjw** [comment]
@oldshuren, can you explain how you called JS from native? The documentation only shows how to call native from JS (with callback).

**Comment by soflare** [comment]
@atwoodjw , thanks for trying the project. Since the project is very young, both document and testing are insufficient.
There are 2 methods for native to JS communication.
1. Evaluate javascript string directly
   WKWebView has async `evaluateJavaScript:completionHandler:` method, XWebView also offers a sync version. See XWebView.swift for details.
2. Access DOM elements through the `scriptObject` property
   When a plugin object `foo` is bound, `foo.scriptObject?.windowObject` is the reference of the window object. For example, to get the value of `window.test`, the swift expression should be `foo.scriptObject?.windowObject["test"]`. For the detail API, check the XWVScriptObject.swift file.

**Comment by atwoodjw** [comment]
Awesome, thank you. Loving the project so far.
